### ISSUE TITLE
Mod will not load

### ISSUE THREAD

**Issue by ayhuz** [Draylar/crimson-moon#1]
When i try to load the mod it gives me this message "Could not find required mod: crimsonmoon requires {fabricloader @ [>=0.8.2+build.194]}" but there are no mods under the relations tab.

**Comment by Draylar** [comment]
Try [updating Fabric loader](https://fabricmc.net/use/). If you're using MultiMC, you can right click your profile, then uninstall & reinstall the loader in the _Version_ tab. If that doesn't work, I would need the entire crash log (which you can upload to a site like [pastebin](https://pastebin.com/)). Thanks!

**Comment by ayhuz** [comment]
Thanks i updated it and it seems to be working :D
