### ISSUE TITLE
The moon should rise crimson or else fade in

### ISSUE THREAD

**Issue by FewerFlaws** [Draylar/crimson-moon#13]
Right now the moon suddenly shifts into crimson mode while its visible after rising.  It would be much better for it to look crimson as it passes the horizon.  Alternatively it could fade to crimson over a few seconds.

**Comment by FewerFlaws** [comment]
Even when disabling the crimson tint to the moon itself, the crimson lighting shift is still sudden and jarring.

**Comment by Draylar** [comment]
Fixed in 2.0.0 👍
