### ISSUE TITLE
Carnage causes server crash when used

### ISSUE THREAD

**Issue by Jetspeedzz** [Draylar/crimson-moon#20]
Holding Carnage alone doesn't do anything but when swung it causes the whole server to crash. Other weapons and items seem to function fine. The weapon also works fine in singleplayer.
This is from the crash report

Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.class_1657.method_18381(Lnet/minecraft/class_4050;)F
	at draylar.crimsonmoon.item.CarnageItem.attack(CarnageItem.java:39)
	at draylar.crimsonmoon.network.ServerNetworking.lambda$null$0(ServerNetworking.java:23)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

Im not sure if this is caused by another mod but I'll give a list here
Fabric Mods: 
		adorn: Adorn 1.12.2+1.16.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.9.1-pre
		betternether: Better Nether 5.0.4
		byg: BYG 1.1.5
		cardinal-components: Cardinal Components API 2.7.9
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.9
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		cardinal-components-level: Cardinal Components API (world saves) 2.7.9
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.9
		cardinal-components-util: Cardinal Components API (utilities) 2.7.9
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		cavebiomes: Cave Biomes 0.5.1
		charm: Charm 2.2.2
		cloth-api: Cloth API 1.5.47
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config2: Cloth Config v4 4.10.13
		cloth-datagen-api-v1: Cloth Datagen v1 1.5.47
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.47
		cloth-utils-v1: Cloth Utils v1 1.5.47
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftycuisine: Crafty Cuisine b1.1
		crimsonmoon: Crimson Moon 2.0.1-beta-1.16.5
		eldritch_mobs: Eldritch Mobs 1.6.8
		extraorigins: Extra Origins 1.16.4-6
		fabric: Fabric API 0.30.3+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.2
		fallflyinglib: FallFlyingLib 1.1.0
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.1.0+1.16.3
		libstructure: Libstructure 1.3
		lightstones: Lightstones 1.3.0
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		medievalweapons: Medieval Weapons 1.0.7
		minecraft: Minecraft 1.16.4
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		origins: Origins 0.4.7
		origins-classes: Origins: Classes 1.1.0
		pehkui: Pehkui 1.7.1+21w03a
		phosphor: Phosphor 0.7.1+build.11
		polymorph: Polymorph 0.0.6-1.16.4
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		seasons: Fabric Seasons 1.0.3-BETA
		sit: Sit 1.16.2-9
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		zoob: Monster Of The Ocean Depths 3.0.0
		
Let me know if you need more info!

**Comment by Draylar** [comment]
Thank you for the report, fixed in the next release!
