### ISSUE TITLE
Dedicated Server Crash in 2.0.2

### ISSUE THREAD

**Issue by mahjerion** [Draylar/crimson-moon#22]
Unfortunately can't provide a crash-report or even a log here, as they don't include this bit below:

![image](https://user-images.githubusercontent.com/66142256/109723259-d6cec100-7b7b-11eb-9c55-1404146773d2.png)

Seems to happen with 2.0.2 upon trying to start up the server. I'm not sure if it's an interaction but the report above doesn't seem to be very helpful. Server does start up successfully with 2.0.1 or 2.0.0.

Craft to Exile [Harmony] 2.1.1b is the version with 2.0.2 if you want to try it out. Thanks Draylar!

**Comment by EnterFor** [comment]
I'm playing with this mod pack in the game, hoping to fix this problem

**Comment by Draylar** [comment]
This is actually a Mixin issue, but Fabric's Mixin fork doesn't have the fix yet... so I'll just provide a workaround for now. Thanks for the report.
