### ISSUE TITLE
Optifabric Shaders not compatible with Satin API

### ISSUE THREAD

**Issue by PalgamingHD** [Draylar/crimson-moon#25]
I know this issue was already opened, but that was a year ago and Optifabric was being discontinued. But now Optifabric is getting updates again, so I was wondering if you would be able to try to make the mod without Satin API, I don't know how hard it would be but if you are able to then please try.

**Comment by Draylar** [comment]
1.18.1 now loads shaders with the vanilla system instead of an external library :)
