### ISSUE TITLE
Need some Help

### ISSUE THREAD

**Issue by Sidolicious** [Draylar/crimson-moon#29]
So up until yesterday my modpack was working fine, and now all of a sudden it just wont launch, and gives up an error saying

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'crimsonmoon'!
Exit Code: -1

If i could get some help on how to fix this issue, thatd be fantastic

**Comment by Sidolicious** [comment]
Felt i should mention but croptopia does the exact same thing

**Comment by Sidolicious** [comment]
https://pastebin.com/kz6q3vpq

sorry for all the comments, but there is the crash report

**Comment by Draylar** [comment]
Try deleting the Crimson Moon config file in your `config` directory.

**Comment by Sidolicious** [comment]
> Try deleting the Crimson Moon config file in your `config` directory.

Youre quick! and smart!! thats exactly what i had to do! fixed croptopia aswell! i just figured out like 5 minutes before you replied, thank you for your time!!! im in a super good mood, thank you alot!
