### ISSUE TITLE
Spawn Radius Server Config

### ISSUE THREAD

**Issue by redstonerti** [Draylar/crimson-moon#35]
It would be very nice if you could change the spawn radius of mobs in the server config because the amount of mobs that spawn is insane and it lags the server hard. Of course, you can already reduce the spawn rate but that would make it less difficult.

**Comment by Draylar** [comment]
Fixed in the next update - check out the `maxChunkSpawnRadius` config option. It defaults to 8, but you can pick something around 3-4 for better performance on servers with a bunch of players.
