### ISSUE TITLE
Blood moon effect stuck

### ISSUE THREAD

**Issue by TheButterbrotMan** [Draylar/crimson-moon#37]
Please checkout the issue on my modpackpage. If you have any questions im willing to help! :)

**Comment by TheButterbrotMan** [comment]
https://github.com/TheButterbrotMan/Deathdusk/issues/32

**Comment by TheButterbrotMan** [comment]
Also this happens also when the server, crashes not. So everytime when a bloodmoon expires, the screen stays red.

**Comment by Draylar** [comment]
I've fixed the mentioned client issue (join server during Blood Moon, exit world, client world has an effect). I'm not sure about the last problem you mentioned, but it might be related to this - give the new version a shot and let me know how it goes. Thanks for the report :)
