### ISSUE TITLE
proper blacklist syntax?

### ISSUE THREAD

**Issue by Squeetsquib** [Draylar/crimson-moon#39]
how is the blacklist supposed to look?

  "blacklistModid": [
    "mythicmounts, terrarianslimes"

**Comment by Draylar** [comment]
```json
"blacklistModid": [
    "mythicmounts",
    "terrarianslimes",
    "mymod"
]
```
Let me know if you have any trouble getting it working! :)

**Comment by Squeetsquib** [comment]
thank you!

**Comment by Squeetsquib** [comment]
still getting a crazy amount of slime spawns

**Comment by Squeetsquib** [comment]
{
  //Delay in seconds between each attempt to spawn a new mob in every loaded chunk during a crimson mood. Values less than 5 seconds may start to cause lag.
  "spawnDelaySeconds": 5,
  //Maximum amount of mobs allowed in a chunk when spawning new ones during a crimson moon.
  "maxMobCountPerChunk": 3,
  //Whether or not beds are disabled during a crimson moon.
  "disableBeds": true,
  //Whether the red shader is enabled. Set this to false to disable the shader.
  "enableShader": true,
  //Whether or not the moon should have a red-tinted texture during a crimson moon.
  "customMoonTexture": true,
  //Whether or not rain should have a red-tinted texture during a crimson moon.
  "customRainTexture": true,
  //The average number of days between each Crimson Moon. 20 is approximately one crimson moon every 20 days.
  "averageNightsBetweenCrimsonMoons": 20,
  //Intensity of the red glow of the Crimson Moon. 0.4 is default, 1.0 is none.
  "glowIntensity": 0.4,
  //If true, custom items are enabled. Make sure the values are the same on the client & server. Do not toggle this if you do not want to lose your custom items.
  "enableCustomItems": true,
  //Base damage of the Carnage Weapon.
  "carnageDamage": 5,
  //Maximum number of chunks (as a radius) around a player to spawn entities during a Crimson Moon.
  "maxChunkSpawnRadius": 8,
  //A list of blocked mod IDs for Crimson Moon entity spawns.
  "blacklistModid": [
    "mythicmounts",
    "terrarianslimes"
  ]
  //Blacklist of entity spawn IDs.
  "blacklistedEntityID": [
    "minecraft:slime",
	"terrariaslimes:baby_slime",
	"terrariaslimes:slimeling",
	"terrariaslimes:mother_slime",
	"terrariaslimes:lava_slime",
	"terrariaslimes:jungle_slime",
	"terrariaslimes:illuminant_slime",
	"terrariaslimes:ice_slime",
	"terrariaslimes:green_slime",
	"terrariaslimes:corrupt_slime",
	"terrariaslimes:blue_slime",
	"terrariaslimes:black_slime",
	"terrariaslimes:yellow_slime",
  ]
}
