### ISSUE TITLE
Clarification on issue persisting in 1.16.2

### ISSUE THREAD

**Issue by mahjerion** [Draylar/crimson-moon#8]
Hey, sorry for posting something like this on your issue tracker (not sure how else to contact you) but there's an missing method error that occurs when entering a world with this mod installed. I know your mod is listed for 1.16.1, but looking at the source code I thought it would possible work on 1.16.2 as well.

[Pastebin](https://pastebin.com/bkMPpbux)

Is the crash due to the biome changes that were introduced in 1.16.2? I know Crimson Moon deals with biomes in some cases, otherwise I presume your mod should work fine with 1.16.2.

Cheers!

**Comment by Draylar** [comment]
This is _exactly_ where you should be posting these issues, no worries there, haha.

 Thank you for the log and the details-- yes, 1.16.2 nuked a lot of stuff, including a few utility methods I was using in my mob spawning logic. I just pushed a 1.16.2 version (1.2.3) on GH and CF which should work, let me know if anything breaks. Enjoy!

**Comment by mahjerion** [comment]
Thank you! Will do.
